from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^chart1a/(?P<year>[0-9]+)/$', views.chart1a, name='chart1a'),
	url(r'^chart1b/(?P<year>[0-9]+)/$', views.chart1b, name='chart1b'),
	url(r'^chart2a/(?P<year>[0-9]+)/$', views.chart2a, name='chart2a'),
	url(r'^chart2b/(?P<year>[0-9]+)/$', views.chart2b, name='chart2b'),
	url(r'^chart3/(?P<instn_id>[0-9]+)/$', views.chart3, name='chart3'),
	url(r'^chart4/(?P<date>[0-9]+)/$', views.chart4, name='chart4'),
	url(r'^chart5/(?P<instn_id>[0-9]+)/$', views.chart5, name='chart5'),
	url(r'^chart6/(?P<mod_id>[0-9]+)/$', views.chart6, name='chart6'),
	url(r'^chart7/(?P<topic>[\w]+)/(?P<graddate>[0-9]+)/$', views.chart7, name='chart7'),
	url(r'^chart8/(?P<topic>[\w]+)/(?P<graddate>[0-9]+)/(?P<abbrev>[\w]+)/$', views.chart8, name='chart8'),
	url(r'^history/$', views.history, name='history'),
	url(r'^employed/$', views.employed, name='employed'),
	url(r'^certificate/(?P<training_id>[0-9]+)/(?P<ppant_id>[0-9]+)/$', views.certificate, name='certificate'),
	url(r'^verif/(?P<serial>[\w]+)/$', views.verification, name='verification'),
	url(r'^master/$', views.master, name='master'),
	url(r'^master/modlist/(?P<mod_id>[0-9]+)/$', views.modlist, name='modlist'),
	url(r'^master/participant/$', views.participant_home, name='participant_home'),
	url(r'^master/participant/participant_list/(?P<instn_id>[0-9]+)/$', views.participant_list, name='participant_list'),
	url(r'^master/participant/(?P<ppant_id>[0-9]+)/$', views.participant, name='participant'),
	url(r'^master/participant/(?P<ppant_id>[0-9]+)/update/(?P<availability>.*)/(?P<employment>.*)/(?P<workdetails>.([^/]+))/(?P<remarks>([^/]+))/$', views.update, name='update'),
	url(r'^master/participant/(?P<ppant_id>[0-9]+)/grades/(?P<training_id>[0-9]+)/$', views.participant_grades, name='participant_grades'),
	url(r'^master/module/(?P<mod_id>[0-9]+)/$', views.module, name='module'),
	url(r'^master/module/trainings/(?P<mod_id>[0-9]+)/$', views.module_related, name='module_related'),
	url(r'^master/institution/(?P<instn_id>[0-9]+)/$', views.institution, name='institution'),
	url(r'^master/institution/members/(?P<instn_id>[0-9]+)/$', views.instn_related, name='instn_related'),
	url(r'^master/training/$', views.training_home, name='training_home'),
	url(r'^master/training/(?P<training_id>[0-9]+)/$', views.training, name='training'),
	url(r'^master/training/members/(?P<training_id>[0-9]+)/$', views.training_related, name='training_related'),
	url(r'^test/$', views.test, name='test'),
	url(r'^asms/$', views.asms, name='asms'),
	url(r'^asms/(?P<ppant_id>[0-9]+)/(?P<ip>[^/]+)/(?P<message>.([^/]+))/$', views.text, name='text'),
	url(r'^asms/(?P<category>[\w]+)/(?P<medium>[\w]+)/(?P<ppant_id>[0-9]+)/$', views.timestamp, name='timestamp'),
	url(r'^mail/$', views.mail, name='mail'),
	url(r'^mail/upload/$', views.upload, name='upload'),
	url(r'^mail/(?P<ppant_id>[0-9]+)/(?P<html>[0-1]+)/(?P<subject>[^/]+)/(?P<message>.([^/]+))/$', views.message, name='message'),
	url(r'^mail/(?P<category>[\w]+)/(?P<medium>[\w]+)/(?P<ppant_id>[0-9]+)/$', views.timestamp, name='timestamp'),
	url(r'^(?P<query>.*)/$', views.query, name='query'),
]
